'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Web.taxydema.track
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TAXYTTSIDETA", [Namespace]:="/TAXYTTSIDETA")>  _
    Partial Public Class TAXYTTSIDETA
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private READOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.D1_CourierConnector.My.MySettings.Default.D1_CourierConnector_Web_taxydema_create_TAXYCREATESIDETA
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event READCompleted As READCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="/TAXYTTSIDETA", ResponseNamespace:="/TAXYTTSIDETA", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function READ(ByVal user_details As READUser_details, ByVal tt_code As String, ByRef st_title As String, ByRef pod_date As String, ByRef pod_time As String, ByRef pod_name As String, <System.Xml.Serialization.XmlElementAttribute("tt_rec")> ByRef tt_rec() As READResponseTt_rec) As <System.Xml.Serialization.XmlElementAttribute("st_flag", DataType:="integer")> String
            Dim results() As Object = Me.Invoke("READ", New Object() {user_details, tt_code})
            st_title = CType(results(1),String)
            pod_date = CType(results(2),String)
            pod_time = CType(results(3),String)
            pod_name = CType(results(4),String)
            tt_rec = CType(results(5),READResponseTt_rec())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub READAsync(ByVal user_details As READUser_details, ByVal tt_code As String)
            Me.READAsync(user_details, tt_code, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub READAsync(ByVal user_details As READUser_details, ByVal tt_code As String, ByVal userState As Object)
            If (Me.READOperationCompleted Is Nothing) Then
                Me.READOperationCompleted = AddressOf Me.OnREADOperationCompleted
            End If
            Me.InvokeAsync("READ", New Object() {user_details, tt_code}, Me.READOperationCompleted, userState)
        End Sub
        
        Private Sub OnREADOperationCompleted(ByVal arg As Object)
            If (Not (Me.READCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent READCompleted(Me, New READCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="/TAXYTTSIDETA")>  _
    Partial Public Class READUser_details
        
        Private a_pel_codeField As String
        
        Private a_user_codeField As String
        
        Private a_user_passField As String
        
        '''<remarks/>
        Public Property a_pel_code() As String
            Get
                Return Me.a_pel_codeField
            End Get
            Set
                Me.a_pel_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_user_code() As String
            Get
                Return Me.a_user_codeField
            End Get
            Set
                Me.a_user_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_user_pass() As String
            Get
                Return Me.a_user_passField
            End Get
            Set
                Me.a_user_passField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="/TAXYTTSIDETA")>  _
    Partial Public Class READResponseTt_rec
        
        Private tt_dateField As String
        
        Private tt_timeField As String
        
        Private tt_station_codeField As String
        
        Private tt_station_titleField As String
        
        Private tt_status_codeField As String
        
        Private tt_status_titleField As String
        
        Private tt_remarksField As String
        
        '''<remarks/>
        Public Property tt_date() As String
            Get
                Return Me.tt_dateField
            End Get
            Set
                Me.tt_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_time() As String
            Get
                Return Me.tt_timeField
            End Get
            Set
                Me.tt_timeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_station_code() As String
            Get
                Return Me.tt_station_codeField
            End Get
            Set
                Me.tt_station_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_station_title() As String
            Get
                Return Me.tt_station_titleField
            End Get
            Set
                Me.tt_station_titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_status_code() As String
            Get
                Return Me.tt_status_codeField
            End Get
            Set
                Me.tt_status_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_status_title() As String
            Get
                Return Me.tt_status_titleField
            End Get
            Set
                Me.tt_status_titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tt_remarks() As String
            Get
                Return Me.tt_remarksField
            End Get
            Set
                Me.tt_remarksField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub READCompletedEventHandler(ByVal sender As Object, ByVal e As READCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class READCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property st_title() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_date() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_time() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_name() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property tt_rec() As READResponseTt_rec()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),READResponseTt_rec())
            End Get
        End Property
    End Class
End Namespace
