'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Web.eltaCourier.track
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PELTT01", [Namespace]:="/PELTT01")>  _
    Partial Public Class PELTT01
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private READOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.D1_CourierConnector.My.MySettings.Default.D1_CourierConnector_Web_eltaCourier_create_CREATEAWB
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event READCompleted As READCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="/PELTT01", ResponseNamespace:="/PELTT01", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function READ(ByVal wpel_code As String, <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByVal wpel_user As String, ByVal wpel_pass As String, ByVal wpel_vg As String, ByVal wpel_ref As String, ByVal wpel_flag As String, ByRef st_title As String, ByRef pod_date As String, ByRef pod_time As String, ByRef pod_name As String, <System.Xml.Serialization.XmlElementAttribute("web_status")> ByRef web_status() As READResponseWeb_status, <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> ByRef web_status_counter As String) As <System.Xml.Serialization.XmlElementAttribute("st_flag", DataType:="integer")> String
            Dim results() As Object = Me.Invoke("READ", New Object() {wpel_code, wpel_user, wpel_pass, wpel_vg, wpel_ref, wpel_flag})
            st_title = CType(results(1),String)
            pod_date = CType(results(2),String)
            pod_time = CType(results(3),String)
            pod_name = CType(results(4),String)
            web_status = CType(results(5),READResponseWeb_status())
            web_status_counter = CType(results(6),String)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub READAsync(ByVal wpel_code As String, ByVal wpel_user As String, ByVal wpel_pass As String, ByVal wpel_vg As String, ByVal wpel_ref As String, ByVal wpel_flag As String)
            Me.READAsync(wpel_code, wpel_user, wpel_pass, wpel_vg, wpel_ref, wpel_flag, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub READAsync(ByVal wpel_code As String, ByVal wpel_user As String, ByVal wpel_pass As String, ByVal wpel_vg As String, ByVal wpel_ref As String, ByVal wpel_flag As String, ByVal userState As Object)
            If (Me.READOperationCompleted Is Nothing) Then
                Me.READOperationCompleted = AddressOf Me.OnREADOperationCompleted
            End If
            Me.InvokeAsync("READ", New Object() {wpel_code, wpel_user, wpel_pass, wpel_vg, wpel_ref, wpel_flag}, Me.READOperationCompleted, userState)
        End Sub
        
        Private Sub OnREADOperationCompleted(ByVal arg As Object)
            If (Not (Me.READCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent READCompleted(Me, New READCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="/PELTT01")>  _
    Partial Public Class READResponseWeb_status
        
        Private web_dateField As String
        
        Private web_timeField As String
        
        Private web_stationField As String
        
        Private web_status_titleField As String
        
        '''<remarks/>
        Public Property web_date() As String
            Get
                Return Me.web_dateField
            End Get
            Set
                Me.web_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property web_time() As String
            Get
                Return Me.web_timeField
            End Get
            Set
                Me.web_timeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property web_station() As String
            Get
                Return Me.web_stationField
            End Get
            Set
                Me.web_stationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property web_status_title() As String
            Get
                Return Me.web_status_titleField
            End Get
            Set
                Me.web_status_titleField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub READCompletedEventHandler(ByVal sender As Object, ByVal e As READCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class READCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property st_title() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_date() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_time() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property pod_name() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property web_status() As READResponseWeb_status()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),READResponseWeb_status())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property web_status_counter() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(6),String)
            End Get
        End Property
    End Class
End Namespace
