'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace Web.taxydema.create
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TAXYCREATESIDETA", [Namespace]:="/TAXYCREATESIDETA")>  _
    Partial Public Class TAXYCREATESIDETA
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private INSERTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.D1_CourierConnector.My.MySettings.Default.D1_CourierConnector_Web_taxydema_create_TAXYCREATESIDETA
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event INSERTCompleted As INSERTCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="/TAXYCREATESIDETA", ResponseNamespace:="/TAXYCREATESIDETA", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function INSERT(ByVal user_details As INSERTUser_details, ByVal vg_details As INSERTVg_details, ByRef st_title As String, ByRef taxydema_sideta As String, ByRef taxydema_doc_sideta As String, ByRef taxydema_par_sideta As String, <System.Xml.Serialization.XmlElementAttribute("taxydema_child_no")> ByRef taxydema_child_no() As String) As <System.Xml.Serialization.XmlElementAttribute("st_flag", DataType:="integer")> String
            Dim results() As Object = Me.Invoke("INSERT", New Object() {user_details, vg_details})
            st_title = CType(results(1),String)
            taxydema_sideta = CType(results(2),String)
            taxydema_doc_sideta = CType(results(3),String)
            taxydema_par_sideta = CType(results(4),String)
            taxydema_child_no = CType(results(5),String())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub INSERTAsync(ByVal user_details As INSERTUser_details, ByVal vg_details As INSERTVg_details)
            Me.INSERTAsync(user_details, vg_details, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INSERTAsync(ByVal user_details As INSERTUser_details, ByVal vg_details As INSERTVg_details, ByVal userState As Object)
            If (Me.INSERTOperationCompleted Is Nothing) Then
                Me.INSERTOperationCompleted = AddressOf Me.OnINSERTOperationCompleted
            End If
            Me.InvokeAsync("INSERT", New Object() {user_details, vg_details}, Me.INSERTOperationCompleted, userState)
        End Sub
        
        Private Sub OnINSERTOperationCompleted(ByVal arg As Object)
            If (Not (Me.INSERTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent INSERTCompleted(Me, New INSERTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="/TAXYCREATESIDETA")>  _
    Partial Public Class INSERTUser_details
        
        Private a_pel_codeField As String
        
        Private a_user_codeField As String
        
        Private a_user_passField As String
        
        Private a_pel_sub_codeField As String
        
        '''<remarks/>
        Public Property a_pel_code() As String
            Get
                Return Me.a_pel_codeField
            End Get
            Set
                Me.a_pel_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_user_code() As String
            Get
                Return Me.a_user_codeField
            End Get
            Set
                Me.a_user_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_user_pass() As String
            Get
                Return Me.a_user_passField
            End Get
            Set
                Me.a_user_passField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_pel_sub_code() As String
            Get
                Return Me.a_pel_sub_codeField
            End Get
            Set
                Me.a_pel_sub_codeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="/TAXYCREATESIDETA")>  _
    Partial Public Class INSERTVg_details
        
        Private a_rec_titleField As String
        
        Private a_rec_addressField As String
        
        Private a_rec_areaField As String
        
        Private a_rec_tkField As String
        
        Private a_rec_thl_1Field As String
        
        Private a_rec_thl_2Field As String
        
        Private a_rec_temaxiaField As String
        
        Private a_rec_barosField As Decimal
        
        Private a_rec_sxoliaField As String
        
        Private a_rec_refField As String
        
        Private a_cod_flagField As String
        
        Private a_cod_posoField As Decimal
        
        Private a_cod_dateField As String
        
        Private a_sur_1Field As String
        
        Private a_sur_2Field As String
        
        Private a_sur_3Field As String
        
        '''<remarks/>
        Public Property a_rec_title() As String
            Get
                Return Me.a_rec_titleField
            End Get
            Set
                Me.a_rec_titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_address() As String
            Get
                Return Me.a_rec_addressField
            End Get
            Set
                Me.a_rec_addressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_area() As String
            Get
                Return Me.a_rec_areaField
            End Get
            Set
                Me.a_rec_areaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_tk() As String
            Get
                Return Me.a_rec_tkField
            End Get
            Set
                Me.a_rec_tkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_rec_thl_1() As String
            Get
                Return Me.a_rec_thl_1Field
            End Get
            Set
                Me.a_rec_thl_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_rec_thl_2() As String
            Get
                Return Me.a_rec_thl_2Field
            End Get
            Set
                Me.a_rec_thl_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_rec_temaxia() As String
            Get
                Return Me.a_rec_temaxiaField
            End Get
            Set
                Me.a_rec_temaxiaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_baros() As Decimal
            Get
                Return Me.a_rec_barosField
            End Get
            Set
                Me.a_rec_barosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_sxolia() As String
            Get
                Return Me.a_rec_sxoliaField
            End Get
            Set
                Me.a_rec_sxoliaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_rec_ref() As String
            Get
                Return Me.a_rec_refField
            End Get
            Set
                Me.a_rec_refField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_cod_flag() As String
            Get
                Return Me.a_cod_flagField
            End Get
            Set
                Me.a_cod_flagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_cod_poso() As Decimal
            Get
                Return Me.a_cod_posoField
            End Get
            Set
                Me.a_cod_posoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a_cod_date() As String
            Get
                Return Me.a_cod_dateField
            End Get
            Set
                Me.a_cod_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_sur_1() As String
            Get
                Return Me.a_sur_1Field
            End Get
            Set
                Me.a_sur_1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_sur_2() As String
            Get
                Return Me.a_sur_2Field
            End Get
            Set
                Me.a_sur_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")>  _
        Public Property a_sur_3() As String
            Get
                Return Me.a_sur_3Field
            End Get
            Set
                Me.a_sur_3Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")>  _
    Public Delegate Sub INSERTCompletedEventHandler(ByVal sender As Object, ByVal e As INSERTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class INSERTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property st_title() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property taxydema_sideta() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property taxydema_doc_sideta() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property taxydema_par_sideta() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(4),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property taxydema_child_no() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(5),String())
            End Get
        End Property
    End Class
End Namespace
